export const sports = [
  {
    id: "1",
    name: "Cricket",
    slug: "cricket",
    description: "India's most beloved sport. From IPL to international test matches.",
    icon: "🏏",
    color: "#1e40af",
  },
  {
    id: "2",
    name: "Football",
    slug: "football",
    description: "Growing rapidly with ISL and national team achievements.",
    icon: "⚽",
    color: "#15803d",
  },
  {
    id: "3",
    name: "Badminton",
    slug: "badminton",
    description: "Home to world champions and Olympic medalists.",
    icon: "🏸",
    color: "#b45309",
  },
  {
    id: "4",
    name: "Hockey",
    slug: "hockey",
    description: "India's national sport with a glorious Olympic legacy.",
    icon: "🏑",
    color: "#0369a1",
  },
  {
    id: "5",
    name: "Volleyball",
    slug: "volleyball",
    description: "Rising popularity at Asian and Commonwealth levels.",
    icon: "🏐",
    color: "#7c3aed",
  },
  {
    id: "6",
    name: "Wrestling & MMA",
    slug: "fighting",
    description: "From traditional kushti to UFC and international wrestling.",
    icon: "🥋",
    color: "#be123c",
  },
];

export const tournaments = [
  {
    id: "1",
    name: "ICC Champions Trophy 2025",
    slug: "icc-champions-trophy-2025",
    status: "COMPLETED",
    startDate: "2025-02-19",
    endDate: "2025-03-09",
    location: "Dubai, UAE",
    city: "Dubai",
    country: "UAE",
    latitude: 25.2048,
    longitude: 55.2708,
    sportId: "1",
    sport: sports[0],
    streamingPlatforms: ["Star Sports", "JioHotstar"],
  },
  {
    id: "2",
    name: "Indian Premier League 2025",
    slug: "ipl-2025",
    status: "LIVE",
    startDate: "2025-03-22",
    endDate: "2025-05-25",
    location: "Multiple Cities, India",
    city: "Mumbai",
    country: "India",
    latitude: 19.076,
    longitude: 72.8777,
    sportId: "1",
    sport: sports[0],
    streamingPlatforms: ["JioHotstar"],
  },
  {
    id: "3",
    name: "Indian Super League 2024-25",
    slug: "isl-2024-25",
    status: "LIVE",
    startDate: "2024-09-13",
    endDate: "2025-03-31",
    location: "Multiple Cities, India",
    city: "Kolkata",
    country: "India",
    latitude: 22.5726,
    longitude: 88.3639,
    sportId: "2",
    sport: sports[1],
    streamingPlatforms: ["JioHotstar", "Sony LIV"],
  },
  {
    id: "4",
    name: "BWF World Championships 2025",
    slug: "bwf-world-championships-2025",
    status: "UPCOMING",
    startDate: "2025-08-25",
    endDate: "2025-08-31",
    location: "Paris, France",
    city: "Paris",
    country: "France",
    latitude: 48.8566,
    longitude: 2.3522,
    sportId: "3",
    sport: sports[2],
    streamingPlatforms: ["JioHotstar", "YouTube"],
  },
  {
    id: "5",
    name: "FIH Hockey World Cup 2026",
    slug: "fih-hockey-world-cup-2026",
    status: "UPCOMING",
    startDate: "2026-01-15",
    endDate: "2026-01-31",
    location: "Bhubaneswar, India",
    city: "Bhubaneswar",
    country: "India",
    latitude: 20.2961,
    longitude: 85.8245,
    sportId: "4",
    sport: sports[3],
    streamingPlatforms: ["JioHotstar"],
  },
  {
    id: "6",
    name: "Asian Wrestling Championships 2025",
    slug: "asian-wrestling-2025",
    status: "COMPLETED",
    startDate: "2025-03-25",
    endDate: "2025-03-30",
    location: "Amman, Jordan",
    city: "Amman",
    country: "Jordan",
    latitude: 31.9454,
    longitude: 35.9284,
    sportId: "6",
    sport: sports[5],
    streamingPlatforms: ["UWW TV", "YouTube"],
  },
  {
    id: "7",
    name: "UFC 312",
    slug: "ufc-312",
    status: "COMPLETED",
    startDate: "2025-02-08",
    endDate: "2025-02-08",
    location: "Sydney, Australia",
    city: "Sydney",
    country: "Australia",
    latitude: -33.8688,
    longitude: 151.2093,
    sportId: "6",
    sport: sports[5],
    streamingPlatforms: ["Sony LIV", "UFC Fight Pass"],
  },
  {
    id: "8",
    name: "Asian Volleyball Championships 2025",
    slug: "asian-volleyball-2025",
    status: "UPCOMING",
    startDate: "2025-09-10",
    endDate: "2025-09-20",
    location: "Tehran, Iran",
    city: "Tehran",
    country: "Iran",
    latitude: 35.6892,
    longitude: 51.389,
    sportId: "5",
    sport: sports[4],
    streamingPlatforms: ["YouTube"],
  },
];

export const players = [
  {
    id: "1",
    name: "Virat Kohli",
    slug: "virat-kohli",
    avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Virat_Kohli_during_the_India_vs_Aus_4th_Test_match_at_Narendra_Modi_Stadium_on_09_March_2023.jpg/440px-Virat_Kohli_during_the_India_vs_Aus_4th_Test_match_at_Narendra_Modi_Stadium_on_09_March_2023.jpg",
    bio: "Former India captain and one of the greatest batsmen of all time.",
    birthDate: "1988-11-05",
    birthPlace: "Delhi, India",
    position: "Batsman",
    socialLinks: { twitter: "@imVkohli", instagram: "@virat.kohli" },
    medals: { gold: 0, silver: 0, bronze: 0 },
    sportId: "1",
    sport: sports[0],
    teamId: null,
  },
  {
    id: "2",
    name: "PV Sindhu",
    slug: "pv-sindhu",
    avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/PV_Sindhu_headshot.jpg/440px-PV_Sindhu_headshot.jpg",
    bio: "Olympic silver and bronze medalist in badminton.",
    birthDate: "1995-07-05",
    birthPlace: "Hyderabad, India",
    position: "Singles",
    socialLinks: { twitter: "@Pvsindhu1", instagram: "@pvsindhu1" },
    medals: { gold: 1, silver: 1, bronze: 2 },
    sportId: "3",
    sport: sports[2],
    teamId: null,
  },
  {
    id: "3",
    name: "Neeraj Chopra",
    slug: "neeraj-chopra",
    avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8e/Neeraj_Chopra_Of_India_%28cropped%29.jpg/440px-Neeraj_Chopra_Of_India_%28cropped%29.jpg",
    bio: "Olympic gold medalist in javelin throw. First Indian to win gold in athletics at Olympics.",
    birthDate: "1997-12-24",
    birthPlace: "Khandra, Haryana, India",
    position: "Javelin Throw",
    socialLinks: { twitter: "@Neeraj_chopra1", instagram: "@neeraj____chopra" },
    medals: { gold: 1, silver: 1, bronze: 0 },
    sportId: "6",
    sport: sports[5],
    teamId: null,
  },
  {
    id: "4",
    name: "Sunil Chhetri",
    slug: "sunil-chhetri",
    avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/3/3b/Sunil_Chhetri_Indian_Footballer.jpg/440px-Sunil_Chhetri_Indian_Footballer.jpg",
    bio: "Captain of Indian national football team and all-time top scorer.",
    birthDate: "1984-08-03",
    birthPlace: "Secunderabad, India",
    position: "Forward",
    socialLinks: { twitter: "@chetrisunil11", instagram: "@chetri_sunil11" },
    medals: { gold: 0, silver: 0, bronze: 0 },
    sportId: "2",
    sport: sports[1],
    teamId: null,
  },
  {
    id: "5",
    name: "Rohit Sharma",
    slug: "rohit-sharma",
    avatar: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Rohit_Sharma_2021.jpg/440px-Rohit_Sharma_2021.jpg",
    bio: "Captain of Indian cricket team. Known for his explosive batting.",
    birthDate: "1987-04-30",
    birthPlace: "Nagpur, India",
    position: "Batsman",
    socialLinks: { twitter: "@ImRo45", instagram: "@rohitsharma45" },
    medals: { gold: 0, silver: 0, bronze: 0 },
    sportId: "1",
    sport: sports[0],
    teamId: null,
  },
  {
    id: "6",
    name: "Manpreet Singh",
    slug: "manpreet-singh-hockey",
    avatar: "",
    bio: "Former captain of Indian men's hockey team. Led team to Olympic bronze.",
    birthDate: "1992-06-26",
    birthPlace: "Jalandhar, Punjab, India",
    position: "Midfielder",
    socialLinks: {},
    medals: { gold: 0, silver: 0, bronze: 1 },
    sportId: "4",
    sport: sports[3],
    teamId: null,
  },
];

export const achievements = [
  {
    id: "1",
    title: "ICC Champions Trophy 2025 Winner",
    description: "India defeated New Zealand in the final to win their third Champions Trophy title.",
    date: "2025-03-09",
    category: "INTERNATIONAL",
    playerId: null,
    teamId: null,
    sportId: "1",
  },
  {
    id: "2",
    title: "Olympic Bronze Medal - Hockey",
    description: "Indian men's hockey team won bronze at Tokyo 2020 Olympics after 41 years.",
    date: "2021-08-05",
    category: "INTERNATIONAL",
    playerId: null,
    teamId: null,
    sportId: "4",
  },
  {
    id: "3",
    title: "Olympic Gold - Javelin Throw",
    description: "Neeraj Chopra won India's first Olympic gold in athletics at Tokyo 2020.",
    date: "2021-08-07",
    category: "INTERNATIONAL",
    playerId: "3",
    teamId: null,
    sportId: "6",
  },
  {
    id: "4",
    title: "BWF World Championship Gold",
    description: "PV Sindhu became the first Indian to win BWF World Championships gold.",
    date: "2019-08-25",
    category: "INTERNATIONAL",
    playerId: "2",
    teamId: null,
    sportId: "3",
  },
  {
    id: "5",
    title: "Asian Games Gold - Football",
    description: "Indian football team won gold at the 1962 Asian Games.",
    date: "1962-08-24",
    category: "INTERNATIONAL",
    playerId: null,
    teamId: null,
    sportId: "2",
  },
  {
    id: "6",
    title: "SAFF Championship 2023 Winner",
    description: "India won the SAFF Championship defeating Kuwait in the final.",
    date: "2023-07-04",
    category: "INTERNATIONAL",
    playerId: "4",
    teamId: null,
    sportId: "2",
  },
  {
    id: "7",
    title: "T20 World Cup 2024 Winner",
    description: "India won the ICC T20 World Cup 2024, defeating South Africa in the final.",
    date: "2024-06-29",
    category: "INTERNATIONAL",
    playerId: null,
    teamId: null,
    sportId: "1",
  },
];

export const fundraisers = [
  {
    id: "1",
    playerId: "3",
    player: players[2],
    title: "Training Camp Fund - Neeraj Chopra",
    description: "Support Neeraj's preparation for upcoming Diamond League and World Championships.",
    target: 500000,
    raised: 325000,
    status: "ACTIVE",
    endDate: "2025-08-01",
  },
  {
    id: "2",
    playerId: "2",
    player: players[1],
    title: "Olympic 2028 Preparation - PV Sindhu",
    description: "Fund PV Sindhu's training and travel expenses for LA 2028 qualification.",
    target: 800000,
    raised: 450000,
    status: "ACTIVE",
    endDate: "2025-12-31",
  },
  {
    id: "3",
    playerId: "6",
    player: players[5],
    title: "Hockey Academy Fund",
    description: "Support Manpreet's initiative to build a grassroots hockey academy in Punjab.",
    target: 2000000,
    raised: 890000,
    status: "ACTIVE",
    endDate: "2025-10-15",
  },
];
